### ISSUE TITLE
Error due to boto version

### ISSUE THREAD

**Issue by IanMeyers** [awslabs/ec2-migrate-longer-id#10]
I have both Python 2.7 and 3.5 installed on Mac:

```
a45e60bd15cd:Temp meyersi$ python2.7 migratelongerids.py --status
ap-south-1:
Traceback (most recent call last):
  File "migratelongerids.py", line 394, in <module>
    main()
  File "migratelongerids.py", line 379, in main
    call_status(regions, usersandids, idresources)
  File "migratelongerids.py", line 87, in call_status
    describeid(k, resource_number, resources)
  File "migratelongerids.py", line 240, in describeid
    id_client_response = id_client.describe_identity_id_format(Resource=resourcetype,
AttributeError: 'EC2' object has no attribute 'describe_identity_id_format'
```

**Comment by phoenix-zhu** [comment]
I ran into this issue as well, any solutions?

**Comment by brete** [comment]
you need to be on a newer version of of boto...run:
pip install -U boto3
I have the following version installed:

## %pip show boto3                                                   [0]

Metadata-Version: 2.0
Name: boto3
Version: 1.2.3
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Library/Python/2.7/site-packages
Requires: jmespath, futures, botocore
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  Natural Language :: English
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4

What version do you have installed? You should be using the newest version available...I _THINK_ it will work on 1.2.6, but 1.2.1 is the minimum for describe_id_format...they didn't add describe_identity_id_format until later (my testing just now shows 1.2.6 minimum).
